name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile all Java files
        run: |
          mkdir -p out
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Optionally run a main class
        run: |
          echo "Skipping execution—compile-only CI"
